spring:
  application:
    name: telemetry-ingest
  datasource:
    url: jdbc:postgresql://localhost:5432/wmn_dev
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    telemetry: wmn.telemetry.v1
