
spring:
  application:
    name: telemetry-controller

server:
  port: 8085

kafka:
  bootstrap:
    servers: localhost:9092
  topic:
    chconfigs: wmn.chconfigs.v1
    features: wmn.features.v1
    forecasts: wmn.forecasts.v1
    plans: wmn.chconfigs.v1
    commands: wmn.commands.v1

app:
  websocket:
    stomp-endpoint: /ws/telemetry
    destination-prefix: /topic/telemetry
